cp -rf ~/Coding/ASV/controller /mnt/sshfs/ASV/
cp -rf ~/Coding/ASV/estimator /mnt/sshfs/ASV/
cp -rf ~/Coding/ASV/examples /mnt/sshfs/ASV/
cp -rf ~/Coding/ASV/fileIO /mnt/sshfs/ASV/
cp -rf ~/Coding/ASV/GUI_communication /mnt/sshfs/ASV/
cp -rf ~/Coding/ASV/logging /mnt/sshfs/ASV/
cp -rf ~/Coding/ASV/planner /mnt/sshfs/ASV/
cp -rf ~/Coding/ASV/property /mnt/sshfs/ASV/
cp -rf ~/Coding/ASV/remotecontrol /mnt/sshfs/ASV/
cp -rf ~/Coding/ASV/sensors /mnt/sshfs/ASV/
cp -rf ~/Coding/ASV/timer /mnt/sshfs/ASV/
cp -rf ~/Coding/ASV/communication /mnt/sshfs/ASV
